name: Maven Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package
        
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify -Dcheckstyle.skip

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Dcheckstyle.skip test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
