name: Maven Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build
        run: mvn --batch-mode -DskipTests --update-snapshots package
        
      - name: Run the Maven verify phase
        run: mvn --batch-mode -Dcheckstyle.skip --update-snapshots verify

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Dcheckstyle.skip test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
